version: 2

sources:
  - name: raw
    schema: raw
    description: Raw source data from upstream systems
    tables:
      - name: customers
        description: Raw customer data from CRM system
        columns:
          - name: customer_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: email
            description: Customer email address
            tests:
              - unique
              - not_null
          - name: first_name
            tests:
              - not_null
          - name: last_name
            tests:
              - not_null
          - name: signup_date
            tests:
              - not_null

      - name: orders
        description: Raw order data from e-commerce platform
        columns:
          - name: order_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to customers
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'customers')
                  field: customer_id
          - name: order_date
            tests:
              - not_null
          - name: status
            tests:
              - not_null
              - accepted_values:
                  values: ['completed', 'pending', 'cancelled', 'refunded']

      - name: order_items
        description: Raw order line items
        columns:
          - name: item_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to orders
            tests:
              - not_null
          - name: product_id
            description: Foreign key to products
            tests:
              - not_null
          - name: quantity
            tests:
              - not_null

      - name: products
        description: Raw product catalog
        columns:
          - name: product_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: product_name
            tests:
              - not_null
          - name: category
            tests:
              - not_null
          - name: price
            tests:
              - not_null
